baseURL = "https://hugo.bloecher.de/"
title = "Giesserei Blöcher GmbH"
theme = "bloecher-custom"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = true
enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "rss"]
canonifyURLs = false
relativeURLs = false

[build]
  writeStats = true

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]

[languages]
  [languages.de]
    locale = "de-DE"
    label = "Deutsch"
    contentDir = "content/de"
    weight = 1
    title = "Giesserei Blöcher GmbH"

  [languages.en]
    locale = "en-GB"
    label = "English"
    contentDir = "content/en"
    weight = 2
    title = "Giesserei Blöcher GmbH"

[params]
  environment = "staging"
  companyName = "Giesserei Blöcher GmbH"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
